---
name: Debug
"on":
  push:

jobs:

  debug:
    uses: kdeldycke/workflows/.github/workflows/debug.yaml@v1.8.7
    runs-on:
      - ubuntu-22.04
      - ubuntu-20.04
      - macos-12
      - macos-11
      - windows-2022
      - windows-2019