---
name: Labeller (file-based)
"on":
  pull_request:

jobs:

  labeller:
    uses: kdeldycke/workflows/.github/workflows/labeller-file-based.yaml@v1.4.1
    with:
      extra-rules: |
        "🔌 bar-plugin":
          - meta_package_manager/tests/*bar_plugin*
          - meta_package_manager/bar_plugin/*

        "📦 manager: apm":
          - meta_package_manager/managers/apm*
          - meta_package_manager/tests/*apm*

        "📦 manager: brew":
          - meta_package_manager/managers/homebrew*
          - meta_package_manager/tests/*homebrew*

        "📦 manager: cask":
          - meta_package_manager/managers/homebrew*
          - meta_package_manager/tests/*homebrew*

        "📦 manager: choco":
          - meta_package_manager/managers/chocolatey*
          - meta_package_manager/tests/*chocolatey*

        "📦 manager: composer":
          - meta_package_manager/managers/composer*
          - meta_package_manager/tests/*composer*

        "📦 manager: dnf":
          - meta_package_manager/managers/dnf*
          - meta_package_manager/tests/*dnf*

        "📦 manager: dpkg-like":
          - meta_package_manager/managers/apt*
          - meta_package_manager/managers/dpkg*
          - meta_package_manager/managers/opkg*
          - meta_package_manager/tests/*apt*
          - meta_package_manager/tests/*dpkg*
          - meta_package_manager/tests/*opkg*

        "📦 manager: emerge":
          - meta_package_manager/managers/emerge*
          - meta_package_manager/tests/*emerge*

        "📦 manager: flatpak":
          - meta_package_manager/managers/flatpak*
          - meta_package_manager/tests/*flatpak*

        "📦 manager: gem":
          - meta_package_manager/managers/gem*
          - meta_package_manager/tests/*gem*

        "📦 manager: mas":
          - meta_package_manager/managers/mas*
          - meta_package_manager/tests/*mas*

        "📦 manager: mpm":
          - meta_package_manager/*

        "📦 manager: npm-like":
          - meta_package_manager/managers/npm*
          - meta_package_manager/managers/yarn*
          - meta_package_manager/tests/*npm*
          - meta_package_manager/tests/*yarn*

        "📦 manager: pacman":
          - meta_package_manager/managers/pacman*
          - meta_package_manager/tests/*pacman*

        "📦 manager: pip":
          - meta_package_manager/managers/pip*
          - meta_package_manager/tests/*pip*

        "📦 manager: snap":
          - meta_package_manager/managers/snap*
          - meta_package_manager/tests/*snap*

        "📦 manager: steamcmd":
          - meta_package_manager/managers/steamcmd*
          - meta_package_manager/tests/*steamcmd*

        "📦 manager: vscode":
          - meta_package_manager/managers/vscode*
          - meta_package_manager/tests/*vscode*