---
name: Build & release
"on":
  # Target are chosen so that all commits get a chance to have their build tested.
  push:
    branches:
      - main
  pull_request:

jobs:

  release:
    uses: kdeldycke/workflows/.github/workflows/release.yaml@v1.10.0
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  nuitka-generate-bins:
    name: Generate binaries
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022
        include:
          - os: ubuntu-22.04
            platform: linux
            extension: bin
          - os: macos-12
            platform: macos
            extension: bin
          - os: windows-2022
            platform: windows
            extension: exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          # XXX Nuitka is not ready for Python 3.11 yet.
          python-version: "3.10"
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install poetry
        run: |
          python -m pip install Poetry
      - name: Install package
        run: |
          poetry install --no-interaction --no-ansi
      - name: Install Nuitka in Poetry venv
        # Additional dependencies:
        #   - ordered-set: used by Nuitka for compilation performance
        #   - zstandard: for nuitka's onefile compression
        run: |
          poetry run python -m pip install nuitka ordered-set zstandard
      - name: Nuitka and compilers versions
        run: |
          poetry run python -m nuitka --version
      - name: macOS and Linux - Build binary within Poetry venv
        if: runner.os != 'Windows'
        run: >
          poetry run python -m nuitka
          --standalone --onefile --assume-yes-for-downloads
          --output-dir=./dist/
          --include-package-data=lark
          --nofollow-import-to=*.tests
          meta_package_manager/__main__.py
      - name: Windows - Build binary within Poetry venv
        if: runner.os == 'Windows'
        # XXX "-X utf8" parameter is a workaround for Windows runners redirecting the output of commands
        # to files. See:
        # https://github.com/databrickslabs/dbx/issues/455#issuecomment-1312770919
        # https://github.com/pallets/click/issues/2121#issuecomment-1312773882
        # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
        # https://github.com/Nuitka/Nuitka/blob/ca1ec9e8e10b51d187b589f1d33935c4ed558687/nuitka/utils/ReExecute.py#L73-L74
        run: >
          poetry run python -X utf8 -m nuitka
          --standalone --onefile --assume-yes-for-downloads
          --nofollow-import-to=*.tests
          --output-filename=mpm.${{ matrix.extension }}
          --output-dir=./dist/
          meta_package_manager/__main__.py
      - name: Rename binary
        run: |
          mv ./dist/__main__.${{ matrix.extension }} ./dist/mpm.${{ matrix.extension }}
      - name: Upload binaries
        uses: actions/upload-artifact@v3.1.1
        with:
          name: mpm-${{ matrix.platform }}.${{ matrix.extension }}
          if-no-files-found: error
          path: |
            ./dist/*.exe
            ./dist/*.bin
            ./dist/*.app/**/*
      - name: Binary tests
        run: |
          ./dist/mpm.${{ matrix.extension }} --version
          ./dist/mpm.${{ matrix.extension }} --help
          ./dist/mpm.${{ matrix.extension }} --all-managers managers